### ISSUE TITLE
v850用高速化策の導入

### ISSUE THREAD

**Issue by ytoi** [toppers/athrill#35]
2020年のETロボコンでathrillh側のCPU消費が大きい場合に走行への影響があったため、いくつか改善を加えてみる。

以下のような変更を予定（順次追加する)。

- [ ] EV3アプリ側からの実時間測定できる機構の導入（効果測定用)
- [ ] set_intpri()のsystemコール化による高速化
- [ ] search_regionの高速化

**Comment by tmori** [comment]
@ytoi ご検討ありがとうございます．課題点とか共有いただければ，こちらでも改善案とか検討できますので，共有いただけますと幸いです．
