### ISSUE TITLE
1 ホスト上で複数 Athrill を起動した場合に利用できない機能がある

### ISSUE THREAD

**Issue by mikoto2000** [toppers/athrill#44]
現在の Athrill は、 Athrill 側の待ち受けポートが define による固定値となっていたり、
同一ホスト上への ROS 通信がブロックされていたりするため、
同一ホスト上で複数 Athrill を実行した場合、利用できない機能が存在します。

マルチ ECU システムや、IoT システムの検証の際
1 Athrill ごとにコンテナや VM を立ち上げるのは準備・リソース的に大変ですので、
ひとつのホスト上で複数 Athrill を起動した際にもフル機能を利用できるようにしたいです。

- [リモートデバッグ機能](https://github.com/toppers/athrill/blob/a479a8d4bd858b00e9ba2d47ec759c2d3a3701a2/src/lib/cui/udp/cui_ops_udp.c#L19-L20)
- ROS 通信機能
    - [MROS_PUBLISHER_PORT_NO](https://github.com/toppers/athrill/blob/a479a8d4bd858b00e9ba2d47ec759c2d3a3701a2/src/device/peripheral/mros-dev/mros-src/protocol/cimpl/mros_protocol_publish_cimpl.c#L34)
    - [MROS_SLAVE_PORT_NO](https://github.com/toppers/athrill/blob/a479a8d4bd858b00e9ba2d47ec759c2d3a3701a2/src/device/peripheral/mros-dev/mros-athrill/device/athrill_mros_device.c#L173)
    - [同一ホスト上の Master への通信](https://github.com/toppers/athrill/blob/a479a8d4bd858b00e9ba2d47ec759c2d3a3701a2/src/device/peripheral/mros-dev/mros-src/protocol/cimpl/mros_protocol_master_cimpl.c#L224-L227)
    - [同一ホスト上の Slave への通信](https://github.com/toppers/athrill/blob/a479a8d4bd858b00e9ba2d47ec759c2d3a3701a2/src/device/peripheral/mros-dev/mros-src/protocol/cimpl/mros_protocol_server_proc_cimpl.c#L258-L261)

# 解決案

- 各ポート番号について、 `device_config` で設定できるようにする
- 通信ブロックについては、該当の処理を削除
    - MROS は組み込み向けに作られているため、
      「同一ホスト上通信は共有メモリを利用する」ことを前提としており、
      自 IP アドレスへの ROS 通信を行わないようにしている
    - Athrill では共有メモリによる通信は行われないため、
      単純に該当箇所の削除で問題ないはず

こちらの案で問題無ければ PR 作成いたします。

**Comment by tmori** [comment]
問題ございません，PRありがとうございます！

**Comment by mikoto2000** [comment]
マージありがとうございました！
