### ISSUE TITLE
DW_AT_specificationが含まれているオブジェクトでassertする

### ISSUE THREAD

**Issue by ytoi** [toppers/athrill#51]
ETロボコンの参加者からの指摘。

ユーザープログラムである変更を加えたところ、athrillでassertされるようになった。

> core id num=1
> ROM : START=0x0 SIZE=2048
> RAM : START=0x200000 SIZE=2048
> RAM : START=0x5ff7000 SIZE=10240
> RAM : START=0x7ff7000 SIZE=10240
> ELF SET CACHE RIGION:addr=0x0 size=171 [KB]
> Elf loading was succeeded:0x0 - 0x2aecc : 171.716 KB
> Elf loading was succeeded:0x2aecc - 0x2b464 : 1.408 KB
> ELF SYMBOL SECTION LOADED:index=118
> ELF SYMBOL SECTION LOADED:sym_num=1743
> ELF STRING TABLE SECTION LOADED:index=119
> attr_type=0x47
> ASSERTION FAILED:../../athrill/src/lib/dwarf/data_type/elf_dwarf_struct_type.c:elf_dwarf_build_struct_method:128:0

0x47はDW_AT_specificationであり、これがelf_dwarf_struct_type.cで対応できていない。

**Comment by tmori** [comment]
マージしましたので，クローズします．
