### ISSUE TITLE
region_executable、region_elf_load_from_vaddrが初期化されていない

### ISSUE THREAD

**Issue by yamam** [toppers/athrill#53]
analize_memmap_arguments()で、region_executable、region_elf_load_from_vaddrをTRUEにする処理がありますが、FALSEにする処理がありませんので、未初期化変数アクセスが発生します。(memory sanitizerで確認しました)

関数の最初で以下の初期化処理が必要と思われます。
    memp->region_executable = FALSE;
    memp->region_elf_load_from_vaddr = FALSE;

**Comment by tmori** [comment]
ご連絡ありがとうございます．理解しました．
修正します．
