### ISSUE TITLE
VSCODEのリモート開発機能を使ってwslに接続すると、listコマンドでVSCODEを起動できない

### ISSUE THREAD

**Issue by takasehideki** [toppers/athrill#6]
下記からの転記
https://github.com/tmori/athrill/issues/20

> @ykominami commented 23 days ago
現在では、wslにLinux向けVSCODEをインストールするより、リモート開発機能拡張をを使って、wslに接続することが推奨されています。
wslにはvscode-serverがインストールされます。
現在のathrill/bin/linux/geany.shでは、codeコマンドが存在しなければエラーになります。
リモート開発機能拡張を使っても、listコマンドで表示して欲しい。

**Comment by ykominami** [comment]
vscodeのリモート開発機能拡張を用い、リモートのサーバにアクセスした際、リモートのサーバにvscodeがインストールされるが、codeへのパスが適切に追加設定されないため？、私の環境では!code"と指定するだけでは、vscodeが実行されません。
これについては、他の人の環境ではcodeでよびだされるという指摘も受けましたので、とりあえず、「私の環境ではcodeを指定するだけではvscodeを呼び出せない」という限定をつけさせてください

**Comment by ykominami** [comment]
その後、.bash_profileなどのログイン時に実行されるシェルスクリプトを見直し、vscodeのremote-wsl, remote-sshでterminalを開いたときに、codeへのパスが環境変数PATHに追加設定されていることを確認しました。
また、処理の途中でその設定が上書きされていることにも気が付き、修正しました。
現在はフルパスを指定しなくても、codeを呼び出せる状態になりました。
私の設定のミスでした。すみません。
このissueはクローズいたします。
